version: '3.8'

services:
  backend:
    image: kickof/server:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped

  frontend:
    image: kickof/web:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - APP_URL=http://frontend:3000
      - API_URL=http://server:8000
      - NEXTAUTH_URL=http://frontend:3000
    restart: unless-stopped