version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ${REGISTRY}/${OWNER}/server:${TAG}
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      cache_from:
        - ${REGISTRY}/${OWNER}/web:${TAG}
    image: ${REGISTRY}/${OWNER}/web:${TAG}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://server:8000
    depends_on:
      - server
    restart: unless-stopped