name: Docker Compose Action

on: [push]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository }}/kickof-server
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/kickof-web
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Lowercase owner
        id: lowercase
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Images
        run: |
          # Build and tag images
          docker-compose build
          
          # Push images individually
          docker push "${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}"
          docker push "${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}"
