name: Docker Compose Action

on: [push]

env:
  REGISTRY: ghcr.io
  # github.repository already includes your username/organization and repository name
  BACKEND_IMAGE_NAME: ${{ github.repository }}/server
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/client
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./server  # adjust this to your backend directory
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      # Build and push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./web  # adjust this to your frontend directory
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      # Optional: Display image URLs
      - name: Image URLs
        run: |
          echo "Backend image: ${{ env.BACKEND_IMAGE }}:latest"
          echo "Frontend image: ${{ env.FRONTEND_IMAGE }}:latest"
