name: Docker Compose Action

on: [push]

env:
  REGISTRY: ghcr.io
  # github.repository already includes your username/organization and repository name
  BACKEND_IMAGE_NAME: ${{ github.repository }}/server
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/web
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner
        id: lowercase
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          compose-command: |
            build
            push --progress=plain
            
      - name: Verify Push Status
        run: |
          echo "Verifying push status..."
          docker images "${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}" || echo "Backend image push failed"
          docker images "${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}" || echo "Frontend image push failed"
        continue-on-error: true

      - name: Final Push Status
        if: ${{ success() }}
        run: echo "Push completed successfully for both images!"
      - name: Handle Failure
        if: ${{ failure() }}
        run: echo "Push failed. Check the logs for details."
