name: Docker Compose Action

on: [push]

env:
  REGISTRY: ghcr.io
  # github.repository already includes your username/organization and repository name
  BACKEND_IMAGE_NAME: ${{ github.repository }}/server
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/client
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Execute tests in the running services
        run: |
          docker-compose exec test-app pytest
